import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
import { ruRU } from "@clerk/localizations";
import logo from "../../public/csaLogo.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Центр санитарной авиации",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={ruRU}>
      <html lang="en">
        <body className={inter.className}>
          {/* <div className="w-full bg-white px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64">
            <Navbar />
          </div> */}

          {/* <div className="px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64"> */}
          {children}
          {/* </div> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
