import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import { ClerkProvider, SignIn } from "@clerk/nextjs";
import { ruRU } from "@clerk/localizations";
import logo from "../../public/csaLogo.png";
import LoadingIndicator from "./components/LoadingSpinner";
import { LoadingProvider } from "./components/LoadingContext";
import LoadingSpinner from "./components/LoadingSpinner";

const roboto = Roboto({ 
  weight: ["400", "700"], // Specify the weights you need
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Центр санитарной авиации",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LoadingProvider>
    <ClerkProvider localization={ruRU}>
      <html lang="en">
        <body className={roboto.className}>
          {/* <div className="w-full bg-white px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64">
            <Navbar />
          </div> */}
          <LoadingSpinner/>
          {/* <div className="px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64"> */}
          {children}
          {/* </div> */}
        </body>
      </html>
    </ClerkProvider>
    </LoadingProvider>
  );
}
